### ISSUE TITLE
How should we run develop mode for this project?

### ISSUE THREAD

**Issue by SeyyedKhandon** [samayo/vuejs-hello-app#2]
I wonder how should we run the develop mode for this, as it only has build mode, can you please guide about it?

Actually I want to use `npm run serve` , to run it and develop the component, and when it has been finished, I just run the `build` to get the proper output

**Comment by samayo** [comment]
Npm run dev

I used that to run as dev and: npm run build. for building

**Comment by SeyyedKhandon** [comment]
Well, it should have a proper script in package.json, so what should I use in script ? ` "dev": "webpack -d"` ?

and since it doesn't have any package.json, I couldn't install it, can you help with this too?

**Comment by samayo** [comment]
Have you followed the tutorial? If you follow it and create your own side-by-side, you won't have any issues. 

To install it, you just need to run `npm install vuejs-hello-app`

For the package.json, I left it semi-empty because this repo was an answer on SO to show how to create a vue component. It is not to be used at all. If you want to know what to put in your package file, use::
```json
    "dev": "webpack-dev-server",
    "build": "webpack --mode production",
``` 
inside `scripts: {}`

**Comment by SeyyedKhandon** [comment]
Thanks, but it won't work(I've installed the webpack-cli, webpack-dev-server etc...).

I followed your answer and comments on StackOverflow, also rea the mentioned document(and lots of other docs).
Actually I've been confused and lost on `How to create and publish multiple Vuejs components on NPM using storybook and lerna?` which is on https://stackoverflow.com/questions/62513076/how-to-create-and-publish-multiple-vuejs-components-on-npm-using-storybook-and-l 
It will be great if you have time, guide me on this question🙏

**Comment by samayo** [comment]
First what do you mean "it won't work"? What did you do, and what is the error you are getting? 
Second, what are you trying to achieve? Do you want to create your own vuejs library and publish it on NPM? 
Let me know so I can help you.

**Comment by SeyyedKhandon** [comment]
Yes I want to publish my vuejs library, currently i'm using typescript and vuejs composition-api in regular development, can you help me on this to make the basic configuration?

**Comment by samayo** [comment]
I haven't used TS or the composition-api with vue. Have you followed this tutorial? https://medium.freecodecamp.org/how-to-create-a-vue-js-app-using-single-file-components-without-the-cli-7e73e5b8244f let me know what you think first because I work full time and don't really get the chance to do something else
